version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Core"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Test"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily