version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Test"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Core"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy"
    schedule:
      interval: "daily"
  - package-ecosystem:  "npm"
    directory: "/ValorDolarHoy/ClientApp"
    schedule: 
      interval: "daily"
      