version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ValorDolarHoy/ClientApp"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Core"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "nuget"
    directory: "/ValorDolarHoy.Test"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
